jobs:
- job: 'Windows_CI'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name pyMORenv
    displayName: Create Anaconda environment
  - script: |
        call activate pyMORenv
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install --only-deps pymor
        REM these ones are not in the 0.5.1 conda build yet
        conda install pyevtk gmsh
        REM these are build/test-time deps for the conda package, not runtime
        conda install cython pytest pytest-cov curl
        REM install anythin which might a niew dependency with pip
        pip install pytest-azurepipelines
    displayName: Install Anaconda packages
